var arrLang={
    'english':{
        'Home' : 'Home',
        'About' : 'About',
        'AboutCompany' : 'About Company',
        'DecisionEstablish':'Decision to establish Company',
        'Branches':'Branches',
        'Projects':'Projects',
        'Archives':'News Archives',
        'Vision':'Vision And Mission',
        'Organozational':'Organozational Structure',
        'Achievements':'Achievements',
        'Awareness':'Awareness',
        'AwarenessMethod':'Awareness Methodology',
        'Kids':'Kids Corner',
        'You':'For You',
        'Quality':'Quality of water',
        'purification':'Drinking Water purification',
        'Laboratory':'Central Laboratory',
        'Tenders':'Tenders',
        'TendersComapny':'All Tenders available in the comapny',
        'WasteWater':'Waste Water',
        'WasteWaterTreatment':'Waste Water Treatment',
        'disposalWastewater':'The importance of safe disposal of Waste Water',
        'RawaWstewater':'Raw waste water treatment and types of treatment stations',
        'maintainingWastewater':'The importance of maintaining the waste water network',
        'roleIndustrialWastewater':'The role of the industrial waste water department ',
        'industrialWastewater':'Industrial waste water',
        'Traning':'Traning',
        'TraningType':'Types of traning and halls',
        'SchoolResult':'School Result',
        'Careers':'Careers',
        'Competitions':'Competitions and Jobs',
        'CompetitionsResults':'Competitions Results',
        'Services':'Services',
        'BillInquire':'Bill Inquire',
        'CustomerService':'Customer Service',
        'CustomerCharter':'Customer Charter',
        'ServiceGuide':'Service guide',
        'stepsContract':'Customer steps to contract a service request',
        'SubmitRequest':'Submit a Request',
        'SubmitComplaint':'Submit a Complaint',
        'IntegritySupport':'Integrity Support',
        'briefIntegritySupport':'Brief about Integrity Support',
        'importantIntegritySupport':'The most important work to Integrity Support',
        'FunctionalBehaviour':'Functional behaviour',
        'Photo':'Photo Gallery',
        'ChairmanTour':'Chairman of the board tours',
        'companyLabo':'Company Laboratories',
        'WastewaterStations':'Waste water stations',
        'TraningCenter':'Traning Center',
        'ITSector':'Information technology sector',
        'TechnicalSchool':'Technical school',
        'SportActivities':'Sport activities',
        'marquee':'Al-Sharqawi inspects the Al-Nazla Al-Kubra Candidate watching the training of technicians on occupational safety and health tasks in the chlorine ward',
        'Latest News':'Latest News',
        'ChairmanMessage':'Chairman"s Message',
        'message1':'Water is the beating heart of life, and it is the basic component of everything that exists on the surface of the earth,in accordance with the words from Quran',
        'Quraan':'(We created from water every living thing وَجَعَلْنَا مِنَ الْمَاء كُلَّ شَيْءٍ حَيٍّ)',
        'message2':'If it were not for water, life would not exist, as its presence is the main reason for the existence of life, and one of God’s blessings upon us is that He granted our beloved Egypt the great Nile River, which represents the lifeline.',
        'message3':'Which calls for the necessity of giving it great values that lie behind its true status, which requires preserving every drop of it, and denying all wrong uses and behaviors in dealing with it.',
        'EngName':'Eng. Ali Abdul Rahman Al-Sharqawi',
        'service':'Service',
        'service1':'Qraaty App',
        'Details-service1':'It allows the citizen to record the meter reading himself, and add a picture of the meter, provided that the readings are sent from the 1st to the 15th of each month to all companies affiliated with the holding company.',
        'btnservice':'Read More',
        'service2':'Hotline App',
        'Details-service2':'It allows the citizen to complaint and suggestion can be sent to the company, and sending notifications to citizens of malfunctions and fractures, alerts about dates of water outages and maintenance work, and paying the bill',
        'service3':'Insert a Reading',
        'Details-service3':'It allows electronic payment of the water and waste water bill in the governorates of (Cairo, Giza, Menoufia, Beheira, Kafr El-Sheikh, Sohag, Alexandria, Red Sea, Matrouh, and Sinai), and it is being activated in the rest of the governorates.',
        'service4':'Bill Inquire',
        'Details-service4':'It allows calculating the value of the monthly bill for the amount of water consumed according to the pricing approved by the Presidency of the Council of Ministers',
        'Employee':'Employee',
        'Lab':'Lab',
        'Subscriber':'Subscriber',
        'Drinking water Station':'Drinking water Station',
        'Waste water station':'Waste water station'
        ,'Sites':'Sites',
        'Project':'Project',
        'Technical School':'',
        'Tenders':'Tenders',
        'Customer Service':'Customer Service',
        'Administration of Training':'Administration of Training',
        'Subscribe to our newsletter to receive all new updates':'Subscribe to our newsletter to receive all new updates',
        'Latest News':'Latest News',
        'title-slide1':'Assuit And New Valley Company For Water And Waste Water',
        'slide1':'We welcome you and we are proud that we are one of the leading companies in the Arab Repblic of Egypt',
        'title-slide2':'Laboratories at the highest level',
        'slide2':'Interest to World Health Organization standars to ensure water quality using the latest standars and technologies',
        'title-slide3':'Customer Service Center',
        'slide3':'Customer service centers, communication methods, and the address of the nearest branch',
        'slide4':'To Download Qraaty Application Press Here',
        'slide5':'To Download Hotline Application Press Here',
        'footer1':'About Us',
        'footer1.1':'Main branch address: Waste Water Station, Abdel Lah House Assiut',
        'footer2':'Headquarter',
        'footer3':'The Assiut and New Valley Water and Wastewater Company was established in 1981 as a public sector company for the purpose of managing, operating and developing water facilities in the various governorate departments. With the issuance of Republican Decree No. 135 of 2004, the company became one of the subsidiaries of the Holding Company for Potable Water and Wastewater',
        'footer4':'Headquarters of the Technical School for Water and waste water in Assiut and New Valley - New Assiut'
    },
    'arabic':{
        'Home' : 'الرئيسيه',
        'About' : 'عن الشركه',
        'AboutCompany' : 'نبذة عن الشركه',
        'DecisionEstablish':'قرار إنشاء الشركه',
        'Branches':'فروع الشركه',
        'Projects':'مشروعات الشركه',
        'Archives':'أرشيف الشركه',
        'Vision':'الرؤيه والرساله',
        'Organozational':'الهيكل التنظيمي',
        'Achievements':'إنجازات الشركه',
        'Awareness':'التوعيه و الاتصال',
        'Kids':'ركن الاطفال',
        'You':'لك انت',
        'Quality':'جودة المياه',
        'purification':'تنقية مياه الشرب',
        'Laboratory':'المعمل المركزي لمياه الشرب',
        'Tenders':'المناقصات',
        'TendersComapny':'جميع المناقصات الموجوده في الشركه',
        'WasteWater':'الصرف الصحي',
        'WasteWaterTreatment':'معالجه الصرف الصحي',
        'disposalWastewater':'تعريف بأهميه التخلص من الصرف الصحي',
        'RawaWstewater':'معالجه الصرف الصحي الخام وأنواع محطات المعالجه',
        'maintainingWastewater':'أهميه الحفاظ علي شبكه الصرف الصحي',
        'roleIndustrialWastewater':'دور إداره الصرف الصحي',
        'industrialWastewater':'الصرف الصحي الصناعي',
        'Traning':'التدريب',
        'TraningType':'أنواع التدريب والقاعات',
        'SchoolResult':'نتائج المدرسه',
        'Careers':'وظائف',
        'Competitions':'مسابقات و وظائف',
        'CompetitionsResults':'نتائج المسابقات',
        'Services':'خدمات',
        'BillInquire':'استعلم عن فاتورتك',
        'CustomerService':'خدمه العملاء',
        'CustomerCharter':'ميثاق المتعاملين',
        'ServiceGuide':'دليل الخدمات',
        'stepsContract':'رحله المتعامل للتعاقد علي طلب خدمه',
        'SubmitRequest':'تقديم طلب',
        'SubmitComplaint':'تقديم شكوي',
        'IntegritySupport':'دعم النزاهه',
        'briefIntegritySupport':'نبذه عن إداره دعم النزاهه',
        'importantIntegritySupport':'أبرز أعمال دعم النزاهه',
        'FunctionalBehaviour':'السلوك الوظيفي',
        'Photo':'معرض الصور',
        'ChairmanTour':'جولات رئيس مجلس الإداره',
        'companyLabo':'معامل الشركه',
        'WastewaterStations':'محطات الصرف الصحي',
        'TraningCenter':'مركز التدريب',
        'ITSector':'قطاع تكنولوجيا المعلومات',
        'TechnicalSchool':'المدرسه الفنيه',
        'SportActivities':'النشاط الاجتماعي',
        'marquee':'الشرقاوى يتفقد مرشحة النزلة الكبرى مشاهدا تدريبات الفنيين على مهمات السلامة والصحة المهنية بعنبر الكلور.',
        'Latest News':'أهم الاخبار',
        'ChairmanMessage':'كلمة السيد رئيس مجلس الإداره والعضو المنتدب',
        'message1':'الماء هو القلب النابض للحياة، وهو المكون الأساسي لكل ما هو موجود على سطح الأرض، تصديقاً لقول الله تعالى',
        'Quraan':'(وَجَعَلْنَا مِنَ الْمَاء كُلَّ شَيْءٍ حَيٍّ)،',
        'message2':'فلولا الماء لانعدمت الحياة، فوجوده هو السبب الرئيسي لوجود الحياة، ومن نعم الله علينا أن وهب مصرنا الحبيبة نهر النيل العظيم الذي يمثل شريان الحياة،  ',
        'message3':'الأمر الذي يدعو إلى ضرورة أن نمنحها قيمه عظيمة تكمن وراء مكانتها الحقيقية التي تستلزم الحفاظ على كل قطرة فيها، وتنفى شتى الاستخدامات والسلوكيات الخاطئة في التعامل معها، ﻿وتمكننا من استغلالها الاستغلال الأمثل الذي يضمن بقاءها ودوامها، مما يكفل الكسب للجميع.',
        'EngName':'السيد المُهندس على عبد الرحمن الشرقاوي',
        'service':'خدمتنا',
        'service1':'تطبيق قرائتي',
        'Details-service1':'يتيح للمواطن تسجيل قراءة العداد بنفسه، وإضافة صورة العداد وهو ما يضمن دقة القراءة، على أن ترسل القراءات من يوم 1 إلى 15 من كل شهر وذلك لكل الشركات التابعة للشركة القابضة.'    ,
        'btnservice':'المزيد',
        'service2':'تطبيق الخط الساخن',
        'Details-service2':'يمكن من خلال التطبيق إرسال الشكاوي والمقترحات إلى الشركة كما يتيح ارسال إشعارات للمواطنين بالأعطال والكسور، وتنبيهات بمواعيد انقطاع المياه وأعمال الصيانة ودفع الفاتورة باستخدام التطبيق..',
        'service3':'إدخل قراءه عدادك',
        'Details-service3':'تتيح الخدمة سداد فاتورة مياه الشرب والصرف الصحى الكترونيا بمحافظات (القاهرة، الجيزة، المنوفية، البحيرة، كفرالشيخ، سوهاج، الاسكندرية، البحر الاحمر، مطروح، سيناء)، وجارى تفعيلها بباقى المحافظات.',
        'service4':'استعلم عن فاتورتك',
        'Details-service4':'تتيح حساب قيمة الفاتورة الشهرية نظير كمية المياه المستهلكة، وفقا للتسعيرة المعتمدة من رئاسة مجلس الوزراء، تحقيقا لمبدأ الشفافية، وإمكانية ترشيد الاستهلاك.',
        'Employee':'عامل',
        'Lab':'معمل',
        'Subscriber':'مشترك',
        'Drinking water Station':' محطات الشرب ',
        'Waste water station':' محطات الصرف',
        'Sites':'مواقعنا ',
        'Project':'مشروعتنا',
        'Technical School':'المدرسة الفنيه التابعه لمياه الشرب',
        'Tenders':'المناقصات',
        'Customer Service':'خـدمـة العـمـلاء',
        'Administration of Training':' الإدارة العامه للتدريب',
        'Subscribe to our newsletter to receive all new updates':'اشترك في نشرتنا الإخبارية ليصلك كل جديد',
        'Latest News':'أحدث الاخبار',
        'title-slide1':'   شركة مياه الشرب والصرف الصحي بأسيوط والوادي الجديد ',
        'slide1':'شركة مياه الشرب والصرف الصحي بأسيوط والوادي الجديد ',
        'title-slide2':'   معامل علي اعلي مستوي  ',
        'slide2':'الاهتمام بمعايير منظمة الصحه العالمية للتاكد من جودة المياه بأحدث المعايير والتقنيات',
        'title-slide3':' مركز خدمة العملاء',
        'slide3':' مراكز خدمه العملاء وطرق التواصل وعنوان أقرب فرع  ',
        'slide4':' لتنزيل برنامج قرائتي اضغط هنا ',
        'slide5':' لتنزيل برنامج الخط الساخن أضغط هنا ',
        'footer1':'بيــانـات الشـــركــة',
        'footer1.1':'عنوان الفرع الرئيسى: محطه مياه المرشحه بنزله عباللاه- اسيوط',
        'footer2':'مقـــر الشـــركــة' ,
        'footer3':'شركة مياه الشرب والصرف الصحي بأسيوط و الوادي الجديد أنشأت عام 1981 كشركة قطاع عام بغرض إدارة وتشغيل وتطوير مرافق المياه بدوائر المحافظة المختلفة. بصدور القرار الجمهوري رقم 135 لسنة 2004 أصبحت الشركة احدي الشركات التابعة للشركة القابضة لمياه الشرب والصرف الصحي.',
        'footer4':'مقـــر المدرسة الفنيه لمياه الشرب والصرف الصحي بأسيوط والوادي الجديد -أسيوط الجديدة'
    }
};

$(function(){
    $('.translate').click(function(){
        var lang = $(this).attr('id');
        $('.lang').each(function(index,element){
            $(this).text(arrLang[lang][$(this).attr('key')]);
        });
    });
});